#!/usr/bin/env python2.3
#
#  Copyright 2001 - 2006 Ludek Smid [http://www.ospace.net/]
#
#  This file is part of IGE - Outer Space.
#
#  IGE - Outer Space is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  IGE - Outer Space is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with IGE - Outer Space; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

# tweak PYTHONPATH
import sys
sys.path.insert(0, 'lib')

from igeclient.IClient import IClient
import pprint, traceback
from getpass import getpass

def msgHandler(id, data):
	if id >= 0:
		print 'Message', id, data

def getPlayer(name):
    u = s.getInfo(1)
    for playerID in u.players:
        pl = s.getInfo(playerID)
        if pl.name == name:
            return pl
    return None

#s = IClient('ige.qgir.cz:9080', None, msgHandler, 'IClient/osc')
s = IClient('212.11.104.99:9080', None, msgHandler, None, 'IClient/osc')

if len(sys.argv) != 2:
	print "Usage: osclient LOGIN"
	sys.exit(1)

login = sys.argv[1]

password = getpass("Password: ")

s.connect(login)
s.login('Alpha', login, password)

from code import InteractiveConsole
console = InteractiveConsole(locals())
console.interact()

s.logout()
